language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t aminezaghdoudi/docker-react -f dockerfile.dev .

script:
  - docker run -e CI=true aminezaghdoudi/docker-react npm run test